#!/bin/bash



# Find all files with a .gif extension in the current directory and subdirectories

# and sort them by byte values in a case-insensitive manner.



# Get the list of all files with .gif extension

files=$(find . -type f -name "*.gif" -print | sort -f -b)



# Remove the .gif extension from each file name and print the result

for file in $files; do

	    # Remove the .gif extension and the leading './' from the file name

	        file_no_ext="${file%.gif}"

		    file_no_ext="${file_no_ext#./}"



		        # Print the file name without the .gif extension

			    echo "$file_no_ext"

		    done



		    # Add a new line at the end

		    echo


